// Mined real test INPUTS for the differential corpus (SPEC §5 "mined mldoc/OG
// test inputs", milestone M5). Self-contained: every string is embedded as data
// (no dependency on any clone at runtime).
//
// Provenance:
//  - mldoc-* : extracted from logseq/mldoc OCaml tests (default branch HEAD
//    bedae99 — no v1.5.7 tag exists; nearest are 1.5.5/1.5.8, and
//    test_markdown.ml/test_outline_markdown.ml line counts match the 1.5.7-era
//    cited in SPEC §5). The INPUT is the first OCaml string literal after each
//    `check_aux`/`check_aux2` call (full OCaml escape + line-continuation
//    decoding); definitions and expected-AST strings are not inputs.
//      test_markdown.ml: 99, test_outline_markdown.ml: 91,
//      test_export_markdown.ml: 14, 0 skipped.
//  - og-*    : markdown input strings curated (by reading) from OG graph-parser
//    cljs tests at /aux/koutecky/logseq/og/deps/graph-parser/test/. Org-format
//    (`:org` config) and org-syntax (#+TITLE, [[file:…][…]]) inputs are excluded;
//    a few runtime (str …)-built block-ref/timestamp cases are reconstructed
//    from their literal constants. Files mined: mldoc_test, block_test,
//    extract_test, text_test, property_test.
//
// Output: corpus.mined.json = [{ id:"m###", cat, input }] — deduped, with empties
// and inputs already present in corpus.json / corpus.blocks.json dropped. Committed
// like corpus.blocks.json (NOT gitignored): generated from this committed source.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// [cat, [input, …]] — newest-style grouped-by-source mined inputs.
const SOURCES = [
  ["mldoc-md", [
    "http://testtest/asdasd",
    "[test  normal](http://testtest/asdasd)",
    "[test `normal`](http://testtest/asdasd)",
    "http://testtest/asd*asd",
    " http://testtest/asdasd ",
    "http://test/f.o.o/b.a.r. ",
    "http://test/(foo)bar",
    "http://test/[(foo)b]ar",
    "http://test/[foo)b]ar",
    "http://te(s)t/foobar",
    "http://test/foo{bar}",
    "[label here](http://foobar/path?query=123)",
    "[not label][label](url)",
    "[[page:name]]",
    "[[page://name]]",
    "[abc [[d ef]] gh](../assets/0000.pdf)",
    "[abc [[d]( ef]] gh](../assets/0000.pdf \"title\")",
    "[label](abc(def)gh)",
    "[中文](https://a.b.c.d/e/f%20g(1).h)",
    "[[a]][b](c)",
    "[a](bbb[[ccc \"dd\"]] \"e f\")",
    "[a](<bbb> \"cc\")",
    "[a](bbb[[ccc \"dd\"]][[ff gg hh]] \"ee\")",
    "[label]([[page-ref]])",
    "[[a[b]c]]",
    "[[a [b] c]]",
    "![lab[el]](url-part)",
    "[label](<u r l>)",
    "{{test foo}}",
    "{{{test foo}}}",
    "{{query (and [[test]])}}",
    "{{{embed [[page]]}}}",
    "{{{query [[page [[nested]]]]}}}",
    "{{macroname [[A,B]], ((C,D)), E}}",
    "{{macroname [[A,B]], ((C,D)), E, \"F,G\"}}",
    ":PROPERTIES:\n:type: programming_lang\n:creator: test\n:END:",
    ":PROPERTIES:\n:type: [[programming_lang]]\n:creator: test\n:END:",
    ":PROPERTIES:\n:type: #programming_lang, #clojure\n:creator: test\n:END:",
    ":PROPERTIES:\n:type: [[programming [[clojure]]]]\n:creator: test\n:END:",
    ":PROPERTIES:\n:type: [[programming [[clojure]]]], #test something, [[programming_lang]], {{embed [[page-in-macro]]}}\n:creator: test\n:END:",
    " :PROPERTIES:\n:type: programming_lang\n:creator: test\n:END:",
    ":PROPERTIES:\r\n:now: 1614485729874\n:done: 1614485743195\r\n:END:\n",
    ":PROPERTIES:\r\n:now: 1614485729874\r\n:done: 1614485743195\r\n:END:\r\n",
    "a.b.c:: def\na-b-c::",
    ":PROPERTIES:\r\n:END:\r\n",
    "> a:: b",
    "`codes here`",
    "*aa`*`",
    "**aa`**`",
    "_a`_`",
    "__a`__`",
    "`as*d`*",
    "[as`d](`http://dwdw)",
    "[as`d](http://dwdw)`",
    "\\Delta G",
    "\\DeltaG",
    "\\Delta{}G",
    "*abc*",
    "**abc**",
    "_a_,",
    "*asd`qwe`*",
    "***asd`qwe`***",
    "a * b*",
    "a_b_c",
    "_a _ a_",
    "*a * a*",
    "hello_world_",
    "hello,_world_",
    "111==text==222",
    "111== text==222",
    "#tag.",
    "#tag,",
    "#tag\"",
    "#tag,.?",
    "#a.b.c",
    "#a.b.c.",
    "#a.b.c. defg",
    "#a.[[b c d ]].e.",
    "[^1][label](url)",
    "*a\\*b*",
    "*a\\\\\\*b*",
    "`a\\``",
    "_a*b\\*_",
    "[[\\]]]",
    "[label\\](x)](xxx)",
    "[label](ur\\)l)",
    "[^abc]: 中文",
    ">foo\n>bar",
    ">foo\nbar",
    ">foo\n>\n>bar",
    "\\begin{equation}[a,b,c] x=\\sqrt{b} \\end{equation}",
    "+ line1\n  - heading",
    "+ line1\n  -",
    "- ## TODO text",
    "- ##",
    "- #tag",
    "a:: 1\n#+b: 2",
    "- ```\ncode\n```",
    "- ``` clj :results\n(inc 2)\n```",
  ]],
  ["mldoc-outline", [
    "http://testtest/asdasd",
    "[foo](bar)",
    "[foo]([[bar]])",
    "http://test/(foo)bar",
    "http://test/[(foo)b]ar",
    "http://test/[foo)b]ar",
    "http://te(s)t/foobar",
    "http://test/foo{bar}",
    "[label here](http://foobar/path?query=123)",
    "[not label][label](url)",
    "[[page:name]]",
    "[[page://name]]",
    "[abc [[d ef]] gh](../assets/0000.pdf)",
    "[abc [[d]( ef]] gh](../assets/0000.pdf \"title\")",
    "[label](abc(def)gh)",
    "[中文](https://a.b.c.d/e/f%20g(1).h)",
    "[[a]][b](c)",
    "[a](bbb[[ccc \"dd\"]] \"e f\")",
    "[a](<bbb> \"cc\")",
    "[a](bbb[[ccc \"dd\"]][[ff gg hh]] \"ee\")",
    "[label]([[page-ref]])",
    "[[a[b]c]]",
    "[[a [b] c]]",
    "![lab[el]](url-part)",
    "[label](<u r l>)",
    ":PROPERTIES:\n:type: programming_lang\n:creator: test\n:END:",
    " :PROPERTIES:\n:type: programming_lang\n:creator: test\n:END:",
    ":PROPERTIES:\r\n:now: 1614485729874\n:done: 1614485743195\r\n:END:\n",
    ":PROPERTIES:\r\n:now: 1614485729874\r\n:done: 1614485743195\r\n:END:\r\n",
    "a.b.c:: def\na-b-c::",
    ":PROPERTIES:\r\n:END:\r\n",
    "> a:: b",
    "`codes here`",
    "*aa`*`",
    "**aa`**`",
    "_a`_`",
    "__a`__`",
    "`as*d`*",
    "[as`d](`http://dwdw)",
    "[as`d](http://dwdw)`",
    "*abc*",
    "**abc**",
    "_a_,",
    "*asd`qwe`*",
    "***asd`qwe`***",
    "a * b*",
    "a_b_c",
    "_a _ a_",
    "*a * a*",
    "hello_world_",
    "hello,_world_",
    "111==text==222",
    "111== text==222",
    "#tag.",
    "#tag,",
    "#tag\"",
    "#tag,.?",
    "#a.b.c",
    "#a.b.c.",
    "#a.b.c. defg",
    "#a.[[b c d ]].e.",
    "[^1][label](url)",
    "*a\\*b*",
    "*a\\\\\\*b*",
    "`a\\``",
    "_a*b\\*_",
    "[[\\]]]",
    "[label\\](x)](xxx)",
    "[label](ur\\)l)",
    "SCHEDULED: <2004-12-25 Sat>",
    "SCHEDULED: <2004-12-25 Sat 10:00>",
    "SCHEDULED: <2004-12-25 Sat +1m>",
    "blabla SCHEDULED: <2004-12-25 Sat>",
    "DEADLINE: <2004-12-25 Sat>",
    "DEADLINE: <2004-12-25 Sat 10:00>",
    "DEADLINE: <2004-12-25 Sat +1m>",
    "blabla DEADLINE: <2004-12-25 Sat>",
    "[^abc]: 中文",
    ">foo\n>bar",
    "\\begin{equation}[a,b,c] x=\\sqrt{b} \\end{equation}",
    "+ line1\n  - heading",
    "+ line1\n  -",
    "- ## TODO text",
    "- ##",
    "- #tag",
    "a:: 1\n#+b: 2",
    "- ```\ncode\n```",
    "- test\nSCHEDULED: <2004-12-25 Sat>",
    "# test\nSCHEDULED: <2004-12-25 Sat>",
    "# test\nSCHEDULED: <2004-12-25 Sat>\nsome [[page]]",
    "# test\nSCHEDULED: <2004-12-25 Sat>\nDEADLINE: <2004-12-25 Sat>\nsome [[page]]",
  ]],
  ["mldoc-export", [
    "- text1 ((ref1)) text2",
    "- line1\n  line2\n  - line3\n  line4",
    "- line1\n  line2\n  - > line3\n    > line4",
    "- line1\n  line2\n  - > line3\n    > line4\n    - line5\n      [[line6]]",
    "- line1\n  line2\n  - > line3\n    > line4\n    - line5\n      [[line6]]\n      -\n\tprop:: hahaha\n\t```\n\t  dwdw\n\t  jdiejdie\n\t```",
    "- `key`: content **bold**test",
    "## heading",
    "- **bold** *italic*\ntest",
    "- line1\n  line2\n  - > line3\n    > line4",
    "- line1\n  line2\n  - > line3\n    > line4\n    - line5\n      [[line6]]",
    "- line1\n  line2\n  - > line3\n    > line4\n    - line5\n      [[line6]]",
    "- # line1\n  - ##  TODO line2\n  - line3",
    "- {{cloze content1,content2}}",
    "- {{cloze (content1,content2)}}",
  ]],
  ["og-mldoc", [
    "google.com",
    "http://www.google.com",
    "http://google.com",
    "[google](http://www.google.com)",
    "[google](https://www.google.com)",
    "[[draws/2022-03-06-15-00-28.excalidraw]]",
    "![a pdf](assets/2022-03-06-15-00-28.pdf)",
    "[YouTube](https://www.youtube.com/watch?v=-8ym7pyUs9gL) - [Vimeo](https://vimeo.com/677920303) {{youtube https://www.youtube.com/watch?v=-8ym7pyUs9g}}",
    "```\n: hello\n```",
    "\n  ```\n  hello\n  world\n  ```\n",
    "property:: [[foo]], [[bar]]",
    "tags:: foo, bar, foo",
    "term\n: definition",
  ]],
  ["og-block", [
    "#000000",
    "[[name/with space]]",
    "[[foo]], [[bar]]",
    "[[foo]] [[bar]]",
    "bar",
    "file:///home/x, y.pdf",
    "1000",
    "\"1000\"",
    "[[name/with space]], [[another]]",
    "[[name/with space]], [[another [[nested]]]]",
    "[[name/with space]], [[[[nested]] another]]",
    "[[bar]], [[baz]]",
    "[[bar]], [[nested [[baz]]]]",
    "[[bar]], [[baz, test]]",
    "[[bar]], [[baz, test, [[nested]]]]",
    "[[bar]] test",
    "[[bar]] test [[baz]]",
    "[[bar]] test [[baz]] [[nested [[baz]]]]",
    "#bar, #baz",
    "[[nested [[page]]]], test",
    "bar\nid:: 63f199bc-c737-459f-983d-84acfcda14fe",
    "bar\n  \n  id:: 63f199bc-c737-459f-983d-84acfcda14fe\nblock body",
    "A block\nid:: 63f528da-284a-45d1-ac9c-5d6a7435f6b4",
    "Link to ((63f528da-284a-45d1-ac9c-5d6a7435f6b4))",
    "B block\nref:: ((63f528da-284a-45d1-ac9c-5d6a7435f6b4))",
    "page-ref:: ((63f528da-284a-45d1-ac9c-5d6a7435f6b4))",
    "do something\nDEADLINE: <2023-02-21 Tue>",
    "do something else\nSCHEDULED: <2023-02-20 Mon>",
  ]],
  ["og-extract", [
    "- a\n  - b\n    - c",
    "## hello\n    - world\n      - nice\n        - nice\n      - bingo\n      - world",
    "# a\n## b\n### c\n#### d\n### e\n- f\n  - g\n    - h\n  - i\n- j",
    "foo:: #bar\nbaz:: #bing",
    "- line1\n    - line2\n      - line3\n     - line4",
  ]],
  ["og-text", [
    "foo",
    "comma, separated",
    "one, two, one",
    "foo, #bar",
    "comma, separated, [[page ref]], [[nested [[page]]]], #[[nested [[tag]]]], end",
    "[[foo]]",
    "[[foo]], [[bar]], #baz",
    "[[foo [[bar]]]]",
    "[[foo [[bar]]]], [[baz]]",
    "comma, is ok",
    "#foo, #bar. #baz!",
    "#foo: '#bar'",
    "\"foo, bar\"",
    "\"[[foo]], [[bar]]\"",
    "[[Jan 11th, 2022]] 21:26",
    "[[[[aldsfkd]] a.b/c.d]]",
    "62e98716-9c0b-4253-83e7-7f8e8a23fe19",
    "{\"product process\" true}",
    "false",
    "1609233702047",
    "#533e7d",
    "[[page]]",
    "[[another page]]",
    "[single bracket]",
    "no brackets",
    "[[nested [[page]]]]",
    "- foobar",
    " - foobar",
    "-foobar",
  ]],
  ["og-property", [
    "foo:: bar",
    "hello\nfoo:: bar",
    "hello\nfoo:: bar\nnice:: bingo",
    "hello\nfoo:: bar\nnice:: bingo\nnice",
  ]],
];

const __dir = dirname(fileURLToPath(import.meta.url));

// Dedup against the committed source corpora (don't re-add an existing input).
const existing = new Set();
for (const f of ["corpus.json", "corpus.blocks.json"]) {
  try {
    for (const c of JSON.parse(readFileSync(join(__dir, f), "utf8"))) existing.add(c.input);
  } catch { /* corpus not generated yet — fine */ }
}

const seen = new Set();
const out = [];
let idx = 0;
for (const [cat, arr] of SOURCES) {
  for (const input of arr) {
    if (input === "") continue;        // drop empties
    if (existing.has(input)) continue; // drop dups of existing corpus
    if (seen.has(input)) continue;     // internal dedup
    seen.add(input);
    out.push({ id: `m${String(idx).padStart(3, "0")}`, cat, input });
    idx++;
  }
}

writeFileSync(join(__dir, "corpus.mined.json"), JSON.stringify(out, null, 1));
console.log(`wrote ${out.length} mined corpus inputs`);
