//! mldoc's LaTeX entity table, extracted verbatim from logseq/mldoc
//! `lib/syntax/entity.ml` (339 entries). Generated — do not hand-edit;
//! regenerate via scratchpad/extract-entities.mjs against the mldoc source.
//!
//! A `\\name` (optionally `\\name{}`) whose name is in this table parses to an
//! `Entity` inline; an unknown `\\foo` falls back to plain `foo` (mldoc behavior).

use std::collections::HashMap;
use std::sync::OnceLock;

/// One resolved entity row (mirrors mldoc `Entity.t`).
pub struct Entity {
    pub name: &'static str,
    pub latex: &'static str,
    pub latex_mathp: bool,
    pub html: &'static str,
    pub ascii: &'static str,
    pub unicode: &'static str,
}

/// Look up a LaTeX entity by name (the letters after `\`), e.g. `find("Delta")`.
/// Returns `None` for an unknown name (caller falls back to plain letters, matching
/// mldoc). Case-sensitive (mldoc's table has distinct `Delta`/`delta`, `AA`/`aa`).
pub fn find(name: &str) -> Option<&'static Entity> {
    static MAP: OnceLock<HashMap<&'static str, Entity>> = OnceLock::new();
    let map = MAP.get_or_init(|| {
        ENTITIES
            .iter()
            .map(|&(name, latex, latex_mathp, html, ascii, unicode)| {
                (name, Entity { name, latex, latex_mathp, html, ascii, unicode })
            })
            .collect()
    });
    map.get(name)
}

/// (name, latex, latex_mathp, html, ascii, unicode)
pub static ENTITIES: &[(&str, &str, bool, &str, &str, &str)] = &[
    ("Agrave", "\\`{A}", false, "&Agrave;", "A", "À"),
    ("agrave", "\\`{a}", false, "&agrave;", "a", "à"),
    ("Aacute", "\\'{A}", false, "&Aacute;", "A", "Á"),
    ("aacute", "\\'{a}", false, "&aacute;", "a", "á"),
    ("Acirc", "\\^{A}", false, "&Acirc;", "A", "Â"),
    ("acirc", "\\^{a}", false, "&acirc;", "a", "â"),
    ("Atilde", "\\~{A}", false, "&Atilde;", "A", "Ã"),
    ("atilde", "\\~{a}", false, "&atilde;", "a", "ã"),
    ("Auml", "\\\"{A}", false, "&Auml;", "Ae", "Ä"),
    ("auml", "\\\"{a}", false, "&auml;", "ae", "ä"),
    ("Aring", "\\AA{}", false, "&Aring;", "A", "Å"),
    ("AA", "\\AA{}", false, "&Aring;", "A", "Å"),
    ("aring", "\\aa{}", false, "&aring;", "a", "å"),
    ("AElig", "\\AE{}", false, "&AElig;", "AE", "Æ"),
    ("aelig", "\\ae{}", false, "&aelig;", "ae", "æ"),
    ("Ccedil", "\\c{C}", false, "&Ccedil;", "C", "Ç"),
    ("ccedil", "\\c{c}", false, "&ccedil;", "c", "ç"),
    ("Egrave", "\\`{E}", false, "&Egrave;", "E", "È"),
    ("egrave", "\\`{e}", false, "&egrave;", "e", "è"),
    ("Eacute", "\\'{E}", false, "&Eacute;", "E", "É"),
    ("eacute", "\\'{e}", false, "&eacute;", "e", "é"),
    ("Ecirc", "\\^{E}", false, "&Ecirc;", "E", "Ê"),
    ("ecirc", "\\^{e}", false, "&ecirc;", "e", "ê"),
    ("Euml", "\\\"{E}", false, "&Euml;", "E", "Ë"),
    ("euml", "\\\"{e}", false, "&euml;", "e", "ë"),
    ("Igrave", "\\`{I}", false, "&Igrave;", "I", "Ì"),
    ("igrave", "\\`{i}", false, "&igrave;", "i", "ì"),
    ("Iacute", "\\'{I}", false, "&Iacute;", "I", "Í"),
    ("iacute", "\\'{i}", false, "&iacute;", "i", "í"),
    ("Icirc", "\\^{I}", false, "&Icirc;", "I", "Î"),
    ("icirc", "\\^{i}", false, "&icirc;", "i", "î"),
    ("Iuml", "\\\"{I}", false, "&Iuml;", "I", "Ï"),
    ("iuml", "\\\"{i}", false, "&iuml;", "i", "ï"),
    ("Ntilde", "\\~{N}", false, "&Ntilde;", "N", "Ñ"),
    ("ntilde", "\\~{n}", false, "&ntilde;", "n", "ñ"),
    ("Ograve", "\\`{O}", false, "&Ograve;", "O", "Ò"),
    ("ograve", "\\`{o}", false, "&ograve;", "o", "ò"),
    ("Oacute", "\\'{O}", false, "&Oacute;", "O", "Ó"),
    ("oacute", "\\'{o}", false, "&oacute;", "o", "ó"),
    ("Ocirc", "\\^{O}", false, "&Ocirc;", "O", "Ô"),
    ("ocirc", "\\^{o}", false, "&ocirc;", "o", "ô"),
    ("Otilde", "\\~{O}", false, "&Otilde;", "O", "Õ"),
    ("otilde", "\\~{o}", false, "&otilde;", "o", "õ"),
    ("Ouml", "\\\"{O}", false, "&Ouml;", "Oe", "Ö"),
    ("ouml", "\\\"{o}", false, "&ouml;", "oe", "ö"),
    ("Oslash", "\\O", false, "&Oslash;", "O", "Ø"),
    ("oslash", "\\o{}", false, "&oslash;", "o", "ø"),
    ("OElig", "\\OE{}", false, "&OElig;", "OE", "Œ"),
    ("oelig", "\\oe{}", false, "&oelig;", "oe", "œ"),
    ("Scaron", "\\v{S}", false, "&Scaron;", "S", "Š"),
    ("scaron", "\\v{s}", false, "&scaron;", "s", "š"),
    ("szlig", "\\ss{}", false, "&szlig;", "ss", "ß"),
    ("Ugrave", "\\`{U}", false, "&Ugrave;", "U", "Ù"),
    ("ugrave", "\\`{u}", false, "&ugrave;", "u", "ù"),
    ("Uacute", "\\'{U}", false, "&Uacute;", "U", "Ú"),
    ("uacute", "\\'{u}", false, "&uacute;", "u", "ú"),
    ("Ucirc", "\\^{U}", false, "&Ucirc;", "U", "Û"),
    ("ucirc", "\\^{u}", false, "&ucirc;", "u", "û"),
    ("Uuml", "\\\"{U}", false, "&Uuml;", "Ue", "Ü"),
    ("uuml", "\\\"{u}", false, "&uuml;", "ue", "ü"),
    ("Yacute", "\\'{Y}", false, "&Yacute;", "Y", "Ý"),
    ("yacute", "\\'{y}", false, "&yacute;", "y", "ý"),
    ("Yuml", "\\\"{Y}", false, "&Yuml;", "Y", "Ÿ"),
    ("yuml", "\\\"{y}", false, "&yuml;", "y", "ÿ"),
    ("fnof", "\\textit{f}", false, "&fnof;", "f", "ƒ"),
    ("real", "\\Re", true, "&real;", "R", "ℜ"),
    ("image", "\\Im", true, "&image;", "I", "ℑ"),
    ("weierp", "\\wp", true, "&weierp;", "P", "℘"),
    ("Alpha", "A", false, "&Alpha;", "Alpha", "Α"),
    ("alpha", "\\alpha", true, "&alpha;", "alpha", "α"),
    ("Beta", "B", false, "&Beta;", "Beta", "Β"),
    ("beta", "\\beta", true, "&beta;", "beta", "β"),
    ("Gamma", "\\Gamma", true, "&Gamma;", "Gamma", "Γ"),
    ("gamma", "\\gamma", true, "&gamma;", "gamma", "γ"),
    ("Delta", "\\Delta", true, "&Delta;", "Delta", "Δ"),
    ("delta", "\\delta", true, "&delta;", "delta", "δ"),
    ("Epsilon", "E", false, "&Epsilon;", "Epsilon", "Ε"),
    ("epsilon", "\\epsilon", true, "&epsilon;", "epsilon", "ε"),
    ("varepsilon", "\\varepsilon", true, "&epsilon;", "varepsilon", "ε"),
    ("Zeta", "Z", false, "&Zeta;", "Zeta", "Ζ"),
    ("zeta", "\\zeta", true, "&zeta;", "zeta", "ζ"),
    ("Eta", "H", false, "&Eta;", "Eta", "Η"),
    ("eta", "\\eta", true, "&eta;", "eta", "η"),
    ("Theta", "\\Theta", true, "&Theta;", "Theta", "Θ"),
    ("theta", "\\theta", true, "&theta;", "theta", "θ"),
    ("thetasym", "\\vartheta", true, "&thetasym;", "theta", "ϑ"),
    ("vartheta", "\\vartheta", true, "&thetasym;", "theta", "ϑ"),
    ("Iota", "I", false, "&Iota;", "Iota", "Ι"),
    ("iota", "\\iota", true, "&iota;", "iota", "ι"),
    ("Kappa", "K", false, "&Kappa;", "Kappa", "Κ"),
    ("kappa", "\\kappa", true, "&kappa;", "kappa", "κ"),
    ("Lambda", "\\Lambda", true, "&Lambda;", "Lambda", "Λ"),
    ("lambda", "\\lambda", true, "&lambda;", "lambda", "λ"),
    ("Mu", "M", false, "&Mu;", "Mu", "Μ"),
    ("mu", "\\mu", true, "&mu;", "mu", "μ"),
    ("nu", "\\nu", true, "&nu;", "nu", "ν"),
    ("Nu", "N", false, "&Nu;", "Nu", "Ν"),
    ("Xi", "\\Xi", true, "&Xi;", "Xi", "Ξ"),
    ("xi", "\\xi", true, "&xi;", "xi", "ξ"),
    ("Omicron", "O", false, "&Omicron;", "Omicron", "Ο"),
    ("omicron", "\\textit{o}", false, "&omicron;", "omicron", "ο"),
    ("Pi", "\\Pi", true, "&Pi;", "Pi", "Π"),
    ("pi", "\\pi", true, "&pi;", "pi", "π"),
    ("Rho", "P", false, "&Rho;", "Rho", "Ρ"),
    ("rho", "\\rho", true, "&rho;", "rho", "ρ"),
    ("Sigma", "\\Sigma", true, "&Sigma;", "Sigma", "Σ"),
    ("sigma", "\\sigma", true, "&sigma;", "sigma", "σ"),
    ("sigmaf", "\\varsigma", true, "&sigmaf;", "sigmaf", "ς"),
    ("varsigma", "\\varsigma", true, "&sigmaf;", "varsigma", "ς"),
    ("Tau", "T", false, "&Tau;", "Tau", "Τ"),
    ("Upsilon", "\\Upsilon", true, "&Upsilon;", "Upsilon", "Υ"),
    ("upsih", "\\Upsilon", true, "&upsih;", "upsilon", "ϒ"),
    ("upsilon", "\\upsilon", true, "&upsilon;", "upsilon", "υ"),
    ("Phi", "\\Phi", true, "&Phi;", "Phi", "Φ"),
    ("phi", "\\phi", true, "&phi;", "phi", "φ"),
    ("Chi", "X", false, "&Chi;", "Chi", "Χ"),
    ("chi", "\\chi", true, "&chi;", "chi", "χ"),
    ("acutex", "\\acute x", true, "&acute;x", "'x", "𝑥́"),
    ("Psi", "\\Psi", true, "&Psi;", "Psi", "Ψ"),
    ("psi", "\\psi", true, "&psi;", "psi", "ψ"),
    ("tau", "\\tau", true, "&tau;", "tau", "τ"),
    ("Omega", "\\Omega", true, "&Omega;", "Omega", "Ω"),
    ("omega", "\\omega", true, "&omega;", "omega", "ω"),
    ("piv", "\\varpi", true, "&piv;", "omega-pi", "ϖ"),
    ("partial", "\\partial", true, "&part;", "[partial differential]", "∂"),
    ("alefsym", "\\aleph", true, "&alefsym;", "aleph", "ℵ"),
    ("ETH", "\\DH{}", false, "&ETH;", "D", "Ð"),
    ("eth", "\\dh{}", false, "&eth;", "dh", "ð"),
    ("THORN", "\\TH{}", false, "&THORN;", "TH", "Þ"),
    ("thorn", "\\th{}", false, "&thorn;", "th", "þ"),
    ("dots", "\\dots{}", false, "&hellip;", "...", "…"),
    ("hellip", "\\dots{}", false, "&hellip;", "...", "…"),
    ("middot", "\\textperiodcentered{}", false, "&middot;", ".", "·"),
    ("iexcl", "!`", false, "&iexcl;", "!", "¡"),
    ("iquest", "?`", false, "&iquest;", "?", "¿"),
    ("shy", "\\-", false, "&shy;", "", ""),
    ("ndash", "--", false, "&ndash;", "-", "–"),
    ("mdash", "---", false, "&mdash;", "--", "—"),
    ("quot", "\\textquotedbl{}", false, "&quot;", "\"", "\""),
    ("acute", "\\textasciiacute{}", false, "&acute;", "'", "´"),
    ("ldquo", "\\textquotedblleft{}", false, "&ldquo;", "\"", "“"),
    ("rdquo", "\\textquotedblright{}", false, "&rdquo;", "\"", "”"),
    ("bdquo", "\\quotedblbase{}", false, "&bdquo;", "\"", "„"),
    ("lsquo", "\\textquoteleft{}", false, "&lsquo;", "`", "‘"),
    ("rsquo", "\\textquoteright{}", false, "&rsquo;", "'", "’"),
    ("sbquo", "\\quotesinglbase{}", false, "&sbquo;", ",", "‚"),
    ("laquo", "\\guillemotleft{}", false, "&laquo;", "<<", "«"),
    ("raquo", "\\guillemotright{}", false, "&raquo;", ">>", "»"),
    ("lsaquo", "\\guilsinglleft{}", false, "&lsaquo;", "<", "‹"),
    ("rsaquo", "\\guilsinglright{}", false, "&rsaquo;", ">", "›"),
    ("circ", "\\circ", true, "&circ;", "^", "ˆ"),
    ("vert", "\\vert{}", true, "&#124;", "|", "|"),
    ("brvbar", "\\textbrokenbar{}", false, "&brvbar;", "|", "¦"),
    ("sect", "\\S", false, "&sect;", "paragraph", "§"),
    ("amp", "\\&", false, "&amp;", "&", "&"),
    ("lt", "\\textless{}", false, "&lt;", "<", "<"),
    ("gt", "\\textgreater{}", false, "&gt;", ">", ">"),
    ("tilde", "\\~{}", false, "&tilde;", "~", "~"),
    ("dagger", "\\textdagger{}", false, "&dagger;", "[dagger]", "†"),
    ("Dagger", "\\textdaggerdbl{}", false, "&Dagger;", "[doubledagger]", "‡"),
    ("nbsp", "~", false, "&nbsp;", " ", " "),
    ("ensp", "\\hspace*{.5em}", false, "&ensp;", " ", " "),
    ("emsp", "\\hspace*{1em}", false, "&emsp;", " ", " "),
    ("thinsp", "\\hspace*{.2em}", false, "&thinsp;", " ", " "),
    ("curren", "\\textcurrency{}", false, "&curren;", "curr.", "¤"),
    ("cent", "\\textcent{}", false, "&cent;", "cent", "¢"),
    ("pound", "\\pounds{}", false, "&pound;", "pound", "£"),
    ("yen", "\\textyen{}", false, "&yen;", "yen", "¥"),
    ("euro", "\\texteuro{}", false, "&euro;", "EUR", "€"),
    ("EUR", "\\EUR{}", false, "&euro;", "EUR", "€"),
    ("EURdig", "\\EURdig{}", false, "&euro;", "EUR", "€"),
    ("EURhv", "\\EURhv{}", false, "&euro;", "EUR", "€"),
    ("EURcr", "\\EURcr{}", false, "&euro;", "EUR", "€"),
    ("EURtm", "\\EURtm{}", false, "&euro;", "EUR", "€"),
    ("copy", "\\textcopyright{}", false, "&copy;", "(c)", "©"),
    ("reg", "\\textregistered{}", false, "&reg;", "(r)", "®"),
    ("trade", "\\texttrademark{}", false, "&trade;", "TM", "™"),
    ("minus", "\\minus", true, "&minus;", "-", "−"),
    ("pm", "\\textpm{}", false, "&plusmn;", "+-", "±"),
    ("plusmn", "\\textpm{}", false, "&plusmn;", "+-", "±"),
    ("times", "\\texttimes{}", false, "&times;", "*", "×"),
    ("frasl", "/", false, "&frasl;", "/", "⁄"),
    ("div", "\\textdiv{}", false, "&divide;", "/", "÷"),
    ("frac12", "\\textonehalf{}", false, "&frac12;", "1/2", "½"),
    ("frac14", "\\textonequarter{}", false, "&frac14;", "1/4", "¼"),
    ("frac34", "\\textthreequarters{}", false, "&frac34;", "3/4", "¾"),
    ("permil", "\\textperthousand{}", false, "&permil;", "per thousand", "‰"),
    ("sup1", "\\textonesuperior{}", false, "&sup1;", "^1", "¹"),
    ("sup2", "\\texttwosuperior{}", false, "&sup2;", "^2", "²"),
    ("sup3", "\\textthreesuperior{}", false, "&sup3;", "^3", "³"),
    ("radic", "\\sqrt{\\,}", true, "&radic;", "[square root]", "√"),
    ("sum", "\\sum", true, "&sum;", "[sum]", "∑"),
    ("prod", "\\prod", true, "&prod;", "[product]", "∏"),
    ("micro", "\\textmu{}", false, "&micro;", "micro", "µ"),
    ("macr", "\\textasciimacron{}", false, "&macr;", "[macron]", "¯"),
    ("deg", "\\textdegree{}", false, "&deg;", "degree", "°"),
    ("prime", "\\prime", true, "&prime;", "'", "′"),
    ("Prime", "\\prime{}\\prime", true, "&Prime;", "''", "″"),
    ("infin", "\\propto", true, "&infin;", "[infinity]", "∞"),
    ("infty", "\\infty", true, "&infin;", "[infinity]", "∞"),
    ("prop", "\\propto", true, "&prop;", "[proportional to]", "∝"),
    ("proptp", "\\propto", true, "&prop;", "[proportional to]", "∝"),
    ("not", "\\textlnot{}", false, "&not;", "[angled dash]", "¬"),
    ("land", "\\land", true, "&and;", "[logical and]", "∧"),
    ("wedge", "\\wedge", true, "&and;", "[logical and]", "∧"),
    ("lor", "\\lor", true, "&or;", "[logical or]", "∨"),
    ("vee", "\\vee", true, "&or;", "[logical or]", "∨"),
    ("cap", "\\cap", true, "&cap;", "[intersection]", "∩"),
    ("cup", "\\cup", true, "&cup;", "[union]", "∪"),
    ("int", "\\int", true, "&int;", "[integral]", "∫"),
    ("there4", "\\therefore", true, "&there4;", "[therefore]", "∴"),
    ("sim", "\\sim", true, "&sim;", "~", "∼"),
    ("cong", "\\cong", true, "&cong;", "[approx. equal to]", "≅"),
    ("simeq", "\\simeq", true, "&cong;", "[approx. equal to]", "≅"),
    ("asymp", "\\asymp", true, "&asymp;", "[almost equal to]", "≈"),
    ("approx", "\\approx", true, "&asymp;", "[almost equal to]", "≈"),
    ("ne", "\\ne", true, "&ne;", "[not equal to]", "≠"),
    ("neq", "\\neq", true, "&ne;", "[not equal to]", "≠"),
    ("equiv", "\\equiv", true, "&equiv;", "[identical to]", "≡"),
    ("le", "\\le", true, "&le;", "<=", "≤"),
    ("ge", "\\ge", true, "&ge;", ">=", "≥"),
    ("sub", "\\subset", true, "&sub;", "[subset of]", "⊂"),
    ("subset", "\\subset", true, "&sub;", "[subset of]", "⊂"),
    ("sup", "\\supset", true, "&sup;", "[superset of]", "⊃"),
    ("supset", "\\supset", true, "&sup;", "[superset of]", "⊃"),
    ("nsub", "\\not\\subset", true, "&nsub;", "[not a subset of]", "⊄"),
    ("sube", "\\subseteq", true, "&sube;", "[subset of or equal to]", "⊆"),
    ("nsup", "\\not\\supset", true, "&nsup;", "[not a superset of]", "⊅"),
    ("supe", "\\supseteq", true, "&supe;", "[superset of or equal to]", "⊇"),
    ("forall", "\\forall", true, "&forall;", "[for all]", "∀"),
    ("exist", "\\exists", true, "&exist;", "[there exists]", "∃"),
    ("exists", "\\exists", true, "&exist;", "[there exists]", "∃"),
    ("empty", "\\empty", true, "&empty;", "[empty set]", "∅"),
    ("emptyset", "\\emptyset", true, "&empty;", "[empty set]", "∅"),
    ("isin", "\\in", true, "&isin;", "[element of]", "∈"),
    ("in", "\\in", true, "&isin;", "[element of]", "∈"),
    ("notin", "\\notin", true, "&notin;", "[not an element of]", "∉"),
    ("ni", "\\ni", true, "&ni;", "[contains as member]", "∋"),
    ("nabla", "\\nabla", true, "&nabla;", "[nabla]", "∇"),
    ("ang", "\\angle", true, "&ang;", "[angle]", "∠"),
    ("angle", "\\angle", true, "&ang;", "[angle]", "∠"),
    ("perp", "\\perp", true, "&perp;", "[up tack]", "⊥"),
    ("sdot", "\\cdot", true, "&sdot;", "[dot]", "⋅"),
    ("cdot", "\\cdot", true, "&sdot;", "[dot]", "⋅"),
    ("lceil", "\\lceil", true, "&lceil;", "[left ceiling]", "⌈"),
    ("rceil", "\\rceil", true, "&rceil;", "[right ceiling]", "⌉"),
    ("lfloor", "\\lfloor", true, "&lfloor;", "[left floor]", "⌊"),
    ("rfloor", "\\rfloor", true, "&rfloor;", "[right floor]", "⌋"),
    ("lang", "\\langle", true, "&lang;", "<", "⟨"),
    ("rang", "\\rangle", true, "&rang;", ">", "⟩"),
    ("larr", "\\leftarrow", true, "&larr;", "<-", "←"),
    ("leftarrow", "\\leftarrow", true, "&larr;", "<-", "←"),
    ("gets", "\\gets", true, "&larr;", "<-", "←"),
    ("lArr", "\\Leftarrow", true, "&lArr;", "<=", "⇐"),
    ("Leftarrow", "\\Leftarrow", true, "&lArr;", "<=", "⇐"),
    ("uarr", "\\uparrow", true, "&uarr;", "[uparrow]", "↑"),
    ("uparrow", "\\uparrow", true, "&uarr;", "[uparrow]", "↑"),
    ("uArr", "\\Uparrow", true, "&uArr;", "[dbluparrow]", "⇑"),
    ("Uparrow", "\\Uparrow", true, "&uArr;", "[dbluparrow]", "⇑"),
    ("rarr", "\\rightarrow", true, "&rarr;", "->", "→"),
    ("to", "\\to", true, "&rarr;", "->", "→"),
    ("rightarrow", "\\rightarrow", true, "&rarr;", "->", "→"),
    ("rArr", "\\Rightarrow", true, "&rArr;", "=>", "⇒"),
    ("Rightarrow", "\\Rightarrow", true, "&rArr;", "=>", "⇒"),
    ("darr", "\\downarrow", true, "&darr;", "[downarrow]", "↓"),
    ("downarrow", "\\downarrow", true, "&darr;", "[downarrow]", "↓"),
    ("dArr", "\\Downarrow", true, "&dArr;", "[dbldownarrow]", "⇓"),
    ("Downarrow", "\\Downarrow", true, "&dArr;", "[dbldownarrow]", "⇓"),
    ("harr", "\\leftrightarrow", true, "&harr;", "<->", "↔"),
    ("leftrightarrow", "\\leftrightarrow", true, "&harr;", "<->", "↔"),
    ("hArr", "\\Leftrightarrow", true, "&hArr;", "<=>", "⇔"),
    ("Leftrightarrow", "\\Leftrightarrow", true, "&hArr;", "<=>", "⇔"),
    ("crarr", "\\hookleftarrow", true, "&crarr;", "<-'", "↵"),
    ("hookleftarrow", "\\hookleftarrow", true, "&crarr;", "<-'", "↵"),
    ("arccos", "\\arccos", true, "arccos", "arccos", "arccos"),
    ("arcsin", "\\arcsin", true, "arcsin", "arcsin", "arcsin"),
    ("arctan", "\\arctan", true, "arctan", "arctan", "arctan"),
    ("arg", "\\arg", true, "arg", "arg", "arg"),
    ("cos", "\\cos", true, "cos", "cos", "cos"),
    ("cosh", "\\cosh", true, "cosh", "cosh", "cosh"),
    ("cot", "\\cot", true, "cot", "cot", "cot"),
    ("coth", "\\coth", true, "coth", "coth", "coth"),
    ("csc", "\\csc", true, "csc", "csc", "csc"),
    ("deg", "\\deg", true, "&deg;", "deg", "deg"),
    ("det", "\\det", true, "det", "det", "det"),
    ("dim", "\\dim", true, "dim", "dim", "dim"),
    ("exp", "\\exp", true, "exp", "exp", "exp"),
    ("gcd", "\\gcd", true, "gcd", "gcd", "gcd"),
    ("hom", "\\hom", true, "hom", "hom", "hom"),
    ("inf", "\\inf", true, "inf", "inf", "inf"),
    ("ker", "\\ker", true, "ker", "ker", "ker"),
    ("lg", "\\lg", true, "lg", "lg", "lg"),
    ("lim", "\\lim", true, "lim", "lim", "lim"),
    ("liminf", "\\liminf", true, "liminf", "liminf", "liminf"),
    ("limsup", "\\limsup", true, "limsup", "limsup", "limsup"),
    ("ln", "\\ln", true, "ln", "ln", "ln"),
    ("log", "\\log", true, "log", "log", "log"),
    ("max", "\\max", true, "max", "max", "max"),
    ("min", "\\min", true, "min", "min", "min"),
    ("Pr", "\\Pr", true, "Pr", "Pr", "Pr"),
    ("sec", "\\sec", true, "sec", "sec", "sec"),
    ("sin", "\\sin", true, "sin", "sin", "sin"),
    ("sinh", "\\sinh", true, "sinh", "sinh", "sinh"),
    ("sup", "\\sup", true, "&sup;", "sup", "sup"),
    ("tan", "\\tan", true, "tan", "tan", "tan"),
    ("tanh", "\\tanh", true, "tanh", "tanh", "tanh"),
    ("bull", "\\textbullet{}", false, "&bull;", "*", "•"),
    ("bullet", "\\textbullet{}", false, "&bull;", "*", "•"),
    ("star", "\\star", true, "*", "*", "⋆"),
    ("lowast", "\\ast", true, "&lowast;", "*", "∗"),
    ("ast", "\\ast", true, "&lowast;", "*", "*"),
    ("odot", "\\odot", true, "o", "[circled dot]", "ʘ"),
    ("oplus", "\\oplus", true, "&oplus;", "[circled plus]", "⊕"),
    ("otimes", "\\otimes", true, "&otimes;", "[circled times]", "⊗"),
    ("checkmark", "\\checkmark", true, "&#10003;", "[checkmark]", "✓"),
    ("para", "\\P{}", false, "&para;", "[pilcrow]", "¶"),
    ("ordf", "\\textordfeminine{}", false, "&ordf;", "_a_", "ª"),
    ("ordm", "\\textordmasculine{}", false, "&ordm;", "_o_", "º"),
    ("cedil", "\\c{}", false, "&cedil;", "[cedilla]", "¸"),
    ("oline", "\\overline{~}", true, "&oline;", "[overline]", "‾"),
    ("uml", "\\textasciidieresis{}", false, "&uml;", "[diaeresis]", "¨"),
    ("zwnj", "\\/{}", false, "&zwnj;", "", "‌"),
    ("zwj", "", false, "&zwj;", "", "‍"),
    ("lrm", "", false, "&lrm;", "", "‎"),
    ("rlm", "", false, "&rlm;", "", "‏"),
    ("smile", "\\smile", true, "&#9786;", ":-)", "⌣"),
    ("smiley", "\\smiley{}", false, "&#9786;", ":-)", "☺"),
    ("blacksmile", "\\blacksmiley{}", false, "&#9787;", ":-)", "☻"),
    ("sad", "\\frownie{}", false, "&#9785;", ":-(", "☹"),
    ("clubs", "\\clubsuit", true, "&clubs;", "[clubs]", "♣"),
    ("clubsuit", "\\clubsuit", true, "&clubs;", "[clubs]", "♣"),
    ("spades", "\\spadesuit", true, "&spades;", "[spades]", "♠"),
    ("spadesuit", "\\spadesuit", true, "&spades;", "[spades]", "♠"),
    ("hearts", "\\heartsuit", true, "&hearts;", "[hearts]", "♥"),
    ("heartsuit", "\\heartsuit", true, "&heartsuit;", "[hearts]", "♥"),
    ("diams", "\\diamondsuit", true, "&diams;", "[diamonds]", "♦"),
    ("diamondsuit", "\\diamondsuit", true, "&diams;", "[diamonds]", "♦"),
    ("Diamond", "\\diamond", true, "&diamond;", "[diamond]", "⋄"),
    ("loz", "\\diamond", true, "&loz;", "[lozenge]", "◊"),
];
