//! mldoc's LaTeX entity table, extracted verbatim from logseq/mldoc
//! `lib/syntax/entity.ml` (337 entries after dedup). Generated — do not hand-edit;
//! regenerate via scratchpad/extract-entities.mjs against the mldoc source,
//! then emit `phf_map!` entries (the generator was updated to this format).
//!
//! A `\\name` (optionally `\\name{}`) whose name is in this table parses to an
//! `Entity` inline; an unknown `\\foo` falls back to plain `foo` (mldoc behavior).

use phf::Map;

/// One resolved entity row (mirrors mldoc `Entity.t`).
pub struct Entity {
    pub name: &'static str,
    pub latex: &'static str,
    pub latex_mathp: bool,
    pub html: &'static str,
    pub ascii: &'static str,
    pub unicode: &'static str,
}

/// Look up a LaTeX entity by name (the letters after `\\`), e.g. `find("Delta")`.
/// Returns `None` for an unknown name (caller falls back to plain letters, matching
/// mldoc). Case-sensitive (mldoc's table has distinct `Delta`/`delta`, `AA`/`aa`).
pub fn find(name: &str) -> Option<&'static Entity> {
    MAP.get(name)
}

static MAP: Map<&'static str, Entity> = phf::phf_map! {
    "Agrave" => Entity { name: "Agrave", latex: "\\`{A}", latex_mathp: false, html: "&Agrave;", ascii: "A", unicode: "À" },
    "agrave" => Entity { name: "agrave", latex: "\\`{a}", latex_mathp: false, html: "&agrave;", ascii: "a", unicode: "à" },
    "Aacute" => Entity { name: "Aacute", latex: "\\'{A}", latex_mathp: false, html: "&Aacute;", ascii: "A", unicode: "Á" },
    "aacute" => Entity { name: "aacute", latex: "\\'{a}", latex_mathp: false, html: "&aacute;", ascii: "a", unicode: "á" },
    "Acirc" => Entity { name: "Acirc", latex: "\\^{A}", latex_mathp: false, html: "&Acirc;", ascii: "A", unicode: "Â" },
    "acirc" => Entity { name: "acirc", latex: "\\^{a}", latex_mathp: false, html: "&acirc;", ascii: "a", unicode: "â" },
    "Atilde" => Entity { name: "Atilde", latex: "\\~{A}", latex_mathp: false, html: "&Atilde;", ascii: "A", unicode: "Ã" },
    "atilde" => Entity { name: "atilde", latex: "\\~{a}", latex_mathp: false, html: "&atilde;", ascii: "a", unicode: "ã" },
    "Auml" => Entity { name: "Auml", latex: "\\\"{A}", latex_mathp: false, html: "&Auml;", ascii: "Ae", unicode: "Ä" },
    "auml" => Entity { name: "auml", latex: "\\\"{a}", latex_mathp: false, html: "&auml;", ascii: "ae", unicode: "ä" },
    "Aring" => Entity { name: "Aring", latex: "\\AA{}", latex_mathp: false, html: "&Aring;", ascii: "A", unicode: "Å" },
    "AA" => Entity { name: "AA", latex: "\\AA{}", latex_mathp: false, html: "&Aring;", ascii: "A", unicode: "Å" },
    "aring" => Entity { name: "aring", latex: "\\aa{}", latex_mathp: false, html: "&aring;", ascii: "a", unicode: "å" },
    "AElig" => Entity { name: "AElig", latex: "\\AE{}", latex_mathp: false, html: "&AElig;", ascii: "AE", unicode: "Æ" },
    "aelig" => Entity { name: "aelig", latex: "\\ae{}", latex_mathp: false, html: "&aelig;", ascii: "ae", unicode: "æ" },
    "Ccedil" => Entity { name: "Ccedil", latex: "\\c{C}", latex_mathp: false, html: "&Ccedil;", ascii: "C", unicode: "Ç" },
    "ccedil" => Entity { name: "ccedil", latex: "\\c{c}", latex_mathp: false, html: "&ccedil;", ascii: "c", unicode: "ç" },
    "Egrave" => Entity { name: "Egrave", latex: "\\`{E}", latex_mathp: false, html: "&Egrave;", ascii: "E", unicode: "È" },
    "egrave" => Entity { name: "egrave", latex: "\\`{e}", latex_mathp: false, html: "&egrave;", ascii: "e", unicode: "è" },
    "Eacute" => Entity { name: "Eacute", latex: "\\'{E}", latex_mathp: false, html: "&Eacute;", ascii: "E", unicode: "É" },
    "eacute" => Entity { name: "eacute", latex: "\\'{e}", latex_mathp: false, html: "&eacute;", ascii: "e", unicode: "é" },
    "Ecirc" => Entity { name: "Ecirc", latex: "\\^{E}", latex_mathp: false, html: "&Ecirc;", ascii: "E", unicode: "Ê" },
    "ecirc" => Entity { name: "ecirc", latex: "\\^{e}", latex_mathp: false, html: "&ecirc;", ascii: "e", unicode: "ê" },
    "Euml" => Entity { name: "Euml", latex: "\\\"{E}", latex_mathp: false, html: "&Euml;", ascii: "E", unicode: "Ë" },
    "euml" => Entity { name: "euml", latex: "\\\"{e}", latex_mathp: false, html: "&euml;", ascii: "e", unicode: "ë" },
    "Igrave" => Entity { name: "Igrave", latex: "\\`{I}", latex_mathp: false, html: "&Igrave;", ascii: "I", unicode: "Ì" },
    "igrave" => Entity { name: "igrave", latex: "\\`{i}", latex_mathp: false, html: "&igrave;", ascii: "i", unicode: "ì" },
    "Iacute" => Entity { name: "Iacute", latex: "\\'{I}", latex_mathp: false, html: "&Iacute;", ascii: "I", unicode: "Í" },
    "iacute" => Entity { name: "iacute", latex: "\\'{i}", latex_mathp: false, html: "&iacute;", ascii: "i", unicode: "í" },
    "Icirc" => Entity { name: "Icirc", latex: "\\^{I}", latex_mathp: false, html: "&Icirc;", ascii: "I", unicode: "Î" },
    "icirc" => Entity { name: "icirc", latex: "\\^{i}", latex_mathp: false, html: "&icirc;", ascii: "i", unicode: "î" },
    "Iuml" => Entity { name: "Iuml", latex: "\\\"{I}", latex_mathp: false, html: "&Iuml;", ascii: "I", unicode: "Ï" },
    "iuml" => Entity { name: "iuml", latex: "\\\"{i}", latex_mathp: false, html: "&iuml;", ascii: "i", unicode: "ï" },
    "Ntilde" => Entity { name: "Ntilde", latex: "\\~{N}", latex_mathp: false, html: "&Ntilde;", ascii: "N", unicode: "Ñ" },
    "ntilde" => Entity { name: "ntilde", latex: "\\~{n}", latex_mathp: false, html: "&ntilde;", ascii: "n", unicode: "ñ" },
    "Ograve" => Entity { name: "Ograve", latex: "\\`{O}", latex_mathp: false, html: "&Ograve;", ascii: "O", unicode: "Ò" },
    "ograve" => Entity { name: "ograve", latex: "\\`{o}", latex_mathp: false, html: "&ograve;", ascii: "o", unicode: "ò" },
    "Oacute" => Entity { name: "Oacute", latex: "\\'{O}", latex_mathp: false, html: "&Oacute;", ascii: "O", unicode: "Ó" },
    "oacute" => Entity { name: "oacute", latex: "\\'{o}", latex_mathp: false, html: "&oacute;", ascii: "o", unicode: "ó" },
    "Ocirc" => Entity { name: "Ocirc", latex: "\\^{O}", latex_mathp: false, html: "&Ocirc;", ascii: "O", unicode: "Ô" },
    "ocirc" => Entity { name: "ocirc", latex: "\\^{o}", latex_mathp: false, html: "&ocirc;", ascii: "o", unicode: "ô" },
    "Otilde" => Entity { name: "Otilde", latex: "\\~{O}", latex_mathp: false, html: "&Otilde;", ascii: "O", unicode: "Õ" },
    "otilde" => Entity { name: "otilde", latex: "\\~{o}", latex_mathp: false, html: "&otilde;", ascii: "o", unicode: "õ" },
    "Ouml" => Entity { name: "Ouml", latex: "\\\"{O}", latex_mathp: false, html: "&Ouml;", ascii: "Oe", unicode: "Ö" },
    "ouml" => Entity { name: "ouml", latex: "\\\"{o}", latex_mathp: false, html: "&ouml;", ascii: "oe", unicode: "ö" },
    "Oslash" => Entity { name: "Oslash", latex: "\\O", latex_mathp: false, html: "&Oslash;", ascii: "O", unicode: "Ø" },
    "oslash" => Entity { name: "oslash", latex: "\\o{}", latex_mathp: false, html: "&oslash;", ascii: "o", unicode: "ø" },
    "OElig" => Entity { name: "OElig", latex: "\\OE{}", latex_mathp: false, html: "&OElig;", ascii: "OE", unicode: "Œ" },
    "oelig" => Entity { name: "oelig", latex: "\\oe{}", latex_mathp: false, html: "&oelig;", ascii: "oe", unicode: "œ" },
    "Scaron" => Entity { name: "Scaron", latex: "\\v{S}", latex_mathp: false, html: "&Scaron;", ascii: "S", unicode: "Š" },
    "scaron" => Entity { name: "scaron", latex: "\\v{s}", latex_mathp: false, html: "&scaron;", ascii: "s", unicode: "š" },
    "szlig" => Entity { name: "szlig", latex: "\\ss{}", latex_mathp: false, html: "&szlig;", ascii: "ss", unicode: "ß" },
    "Ugrave" => Entity { name: "Ugrave", latex: "\\`{U}", latex_mathp: false, html: "&Ugrave;", ascii: "U", unicode: "Ù" },
    "ugrave" => Entity { name: "ugrave", latex: "\\`{u}", latex_mathp: false, html: "&ugrave;", ascii: "u", unicode: "ù" },
    "Uacute" => Entity { name: "Uacute", latex: "\\'{U}", latex_mathp: false, html: "&Uacute;", ascii: "U", unicode: "Ú" },
    "uacute" => Entity { name: "uacute", latex: "\\'{u}", latex_mathp: false, html: "&uacute;", ascii: "u", unicode: "ú" },
    "Ucirc" => Entity { name: "Ucirc", latex: "\\^{U}", latex_mathp: false, html: "&Ucirc;", ascii: "U", unicode: "Û" },
    "ucirc" => Entity { name: "ucirc", latex: "\\^{u}", latex_mathp: false, html: "&ucirc;", ascii: "u", unicode: "û" },
    "Uuml" => Entity { name: "Uuml", latex: "\\\"{U}", latex_mathp: false, html: "&Uuml;", ascii: "Ue", unicode: "Ü" },
    "uuml" => Entity { name: "uuml", latex: "\\\"{u}", latex_mathp: false, html: "&uuml;", ascii: "ue", unicode: "ü" },
    "Yacute" => Entity { name: "Yacute", latex: "\\'{Y}", latex_mathp: false, html: "&Yacute;", ascii: "Y", unicode: "Ý" },
    "yacute" => Entity { name: "yacute", latex: "\\'{y}", latex_mathp: false, html: "&yacute;", ascii: "y", unicode: "ý" },
    "Yuml" => Entity { name: "Yuml", latex: "\\\"{Y}", latex_mathp: false, html: "&Yuml;", ascii: "Y", unicode: "Ÿ" },
    "yuml" => Entity { name: "yuml", latex: "\\\"{y}", latex_mathp: false, html: "&yuml;", ascii: "y", unicode: "ÿ" },
    "fnof" => Entity { name: "fnof", latex: "\\textit{f}", latex_mathp: false, html: "&fnof;", ascii: "f", unicode: "ƒ" },
    "real" => Entity { name: "real", latex: "\\Re", latex_mathp: true, html: "&real;", ascii: "R", unicode: "ℜ" },
    "image" => Entity { name: "image", latex: "\\Im", latex_mathp: true, html: "&image;", ascii: "I", unicode: "ℑ" },
    "weierp" => Entity { name: "weierp", latex: "\\wp", latex_mathp: true, html: "&weierp;", ascii: "P", unicode: "℘" },
    "Alpha" => Entity { name: "Alpha", latex: "A", latex_mathp: false, html: "&Alpha;", ascii: "Alpha", unicode: "Α" },
    "alpha" => Entity { name: "alpha", latex: "\\alpha", latex_mathp: true, html: "&alpha;", ascii: "alpha", unicode: "α" },
    "Beta" => Entity { name: "Beta", latex: "B", latex_mathp: false, html: "&Beta;", ascii: "Beta", unicode: "Β" },
    "beta" => Entity { name: "beta", latex: "\\beta", latex_mathp: true, html: "&beta;", ascii: "beta", unicode: "β" },
    "Gamma" => Entity { name: "Gamma", latex: "\\Gamma", latex_mathp: true, html: "&Gamma;", ascii: "Gamma", unicode: "Γ" },
    "gamma" => Entity { name: "gamma", latex: "\\gamma", latex_mathp: true, html: "&gamma;", ascii: "gamma", unicode: "γ" },
    "Delta" => Entity { name: "Delta", latex: "\\Delta", latex_mathp: true, html: "&Delta;", ascii: "Delta", unicode: "Δ" },
    "delta" => Entity { name: "delta", latex: "\\delta", latex_mathp: true, html: "&delta;", ascii: "delta", unicode: "δ" },
    "Epsilon" => Entity { name: "Epsilon", latex: "E", latex_mathp: false, html: "&Epsilon;", ascii: "Epsilon", unicode: "Ε" },
    "epsilon" => Entity { name: "epsilon", latex: "\\epsilon", latex_mathp: true, html: "&epsilon;", ascii: "epsilon", unicode: "ε" },
    "varepsilon" => Entity { name: "varepsilon", latex: "\\varepsilon", latex_mathp: true, html: "&epsilon;", ascii: "varepsilon", unicode: "ε" },
    "Zeta" => Entity { name: "Zeta", latex: "Z", latex_mathp: false, html: "&Zeta;", ascii: "Zeta", unicode: "Ζ" },
    "zeta" => Entity { name: "zeta", latex: "\\zeta", latex_mathp: true, html: "&zeta;", ascii: "zeta", unicode: "ζ" },
    "Eta" => Entity { name: "Eta", latex: "H", latex_mathp: false, html: "&Eta;", ascii: "Eta", unicode: "Η" },
    "eta" => Entity { name: "eta", latex: "\\eta", latex_mathp: true, html: "&eta;", ascii: "eta", unicode: "η" },
    "Theta" => Entity { name: "Theta", latex: "\\Theta", latex_mathp: true, html: "&Theta;", ascii: "Theta", unicode: "Θ" },
    "theta" => Entity { name: "theta", latex: "\\theta", latex_mathp: true, html: "&theta;", ascii: "theta", unicode: "θ" },
    "thetasym" => Entity { name: "thetasym", latex: "\\vartheta", latex_mathp: true, html: "&thetasym;", ascii: "theta", unicode: "ϑ" },
    "vartheta" => Entity { name: "vartheta", latex: "\\vartheta", latex_mathp: true, html: "&thetasym;", ascii: "theta", unicode: "ϑ" },
    "Iota" => Entity { name: "Iota", latex: "I", latex_mathp: false, html: "&Iota;", ascii: "Iota", unicode: "Ι" },
    "iota" => Entity { name: "iota", latex: "\\iota", latex_mathp: true, html: "&iota;", ascii: "iota", unicode: "ι" },
    "Kappa" => Entity { name: "Kappa", latex: "K", latex_mathp: false, html: "&Kappa;", ascii: "Kappa", unicode: "Κ" },
    "kappa" => Entity { name: "kappa", latex: "\\kappa", latex_mathp: true, html: "&kappa;", ascii: "kappa", unicode: "κ" },
    "Lambda" => Entity { name: "Lambda", latex: "\\Lambda", latex_mathp: true, html: "&Lambda;", ascii: "Lambda", unicode: "Λ" },
    "lambda" => Entity { name: "lambda", latex: "\\lambda", latex_mathp: true, html: "&lambda;", ascii: "lambda", unicode: "λ" },
    "Mu" => Entity { name: "Mu", latex: "M", latex_mathp: false, html: "&Mu;", ascii: "Mu", unicode: "Μ" },
    "mu" => Entity { name: "mu", latex: "\\mu", latex_mathp: true, html: "&mu;", ascii: "mu", unicode: "μ" },
    "nu" => Entity { name: "nu", latex: "\\nu", latex_mathp: true, html: "&nu;", ascii: "nu", unicode: "ν" },
    "Nu" => Entity { name: "Nu", latex: "N", latex_mathp: false, html: "&Nu;", ascii: "Nu", unicode: "Ν" },
    "Xi" => Entity { name: "Xi", latex: "\\Xi", latex_mathp: true, html: "&Xi;", ascii: "Xi", unicode: "Ξ" },
    "xi" => Entity { name: "xi", latex: "\\xi", latex_mathp: true, html: "&xi;", ascii: "xi", unicode: "ξ" },
    "Omicron" => Entity { name: "Omicron", latex: "O", latex_mathp: false, html: "&Omicron;", ascii: "Omicron", unicode: "Ο" },
    "omicron" => Entity { name: "omicron", latex: "\\textit{o}", latex_mathp: false, html: "&omicron;", ascii: "omicron", unicode: "ο" },
    "Pi" => Entity { name: "Pi", latex: "\\Pi", latex_mathp: true, html: "&Pi;", ascii: "Pi", unicode: "Π" },
    "pi" => Entity { name: "pi", latex: "\\pi", latex_mathp: true, html: "&pi;", ascii: "pi", unicode: "π" },
    "Rho" => Entity { name: "Rho", latex: "P", latex_mathp: false, html: "&Rho;", ascii: "Rho", unicode: "Ρ" },
    "rho" => Entity { name: "rho", latex: "\\rho", latex_mathp: true, html: "&rho;", ascii: "rho", unicode: "ρ" },
    "Sigma" => Entity { name: "Sigma", latex: "\\Sigma", latex_mathp: true, html: "&Sigma;", ascii: "Sigma", unicode: "Σ" },
    "sigma" => Entity { name: "sigma", latex: "\\sigma", latex_mathp: true, html: "&sigma;", ascii: "sigma", unicode: "σ" },
    "sigmaf" => Entity { name: "sigmaf", latex: "\\varsigma", latex_mathp: true, html: "&sigmaf;", ascii: "sigmaf", unicode: "ς" },
    "varsigma" => Entity { name: "varsigma", latex: "\\varsigma", latex_mathp: true, html: "&sigmaf;", ascii: "varsigma", unicode: "ς" },
    "Tau" => Entity { name: "Tau", latex: "T", latex_mathp: false, html: "&Tau;", ascii: "Tau", unicode: "Τ" },
    "Upsilon" => Entity { name: "Upsilon", latex: "\\Upsilon", latex_mathp: true, html: "&Upsilon;", ascii: "Upsilon", unicode: "Υ" },
    "upsih" => Entity { name: "upsih", latex: "\\Upsilon", latex_mathp: true, html: "&upsih;", ascii: "upsilon", unicode: "ϒ" },
    "upsilon" => Entity { name: "upsilon", latex: "\\upsilon", latex_mathp: true, html: "&upsilon;", ascii: "upsilon", unicode: "υ" },
    "Phi" => Entity { name: "Phi", latex: "\\Phi", latex_mathp: true, html: "&Phi;", ascii: "Phi", unicode: "Φ" },
    "phi" => Entity { name: "phi", latex: "\\phi", latex_mathp: true, html: "&phi;", ascii: "phi", unicode: "φ" },
    "Chi" => Entity { name: "Chi", latex: "X", latex_mathp: false, html: "&Chi;", ascii: "Chi", unicode: "Χ" },
    "chi" => Entity { name: "chi", latex: "\\chi", latex_mathp: true, html: "&chi;", ascii: "chi", unicode: "χ" },
    "acutex" => Entity { name: "acutex", latex: "\\acute x", latex_mathp: true, html: "&acute;x", ascii: "'x", unicode: "𝑥́" },
    "Psi" => Entity { name: "Psi", latex: "\\Psi", latex_mathp: true, html: "&Psi;", ascii: "Psi", unicode: "Ψ" },
    "psi" => Entity { name: "psi", latex: "\\psi", latex_mathp: true, html: "&psi;", ascii: "psi", unicode: "ψ" },
    "tau" => Entity { name: "tau", latex: "\\tau", latex_mathp: true, html: "&tau;", ascii: "tau", unicode: "τ" },
    "Omega" => Entity { name: "Omega", latex: "\\Omega", latex_mathp: true, html: "&Omega;", ascii: "Omega", unicode: "Ω" },
    "omega" => Entity { name: "omega", latex: "\\omega", latex_mathp: true, html: "&omega;", ascii: "omega", unicode: "ω" },
    "piv" => Entity { name: "piv", latex: "\\varpi", latex_mathp: true, html: "&piv;", ascii: "omega-pi", unicode: "ϖ" },
    "partial" => Entity { name: "partial", latex: "\\partial", latex_mathp: true, html: "&part;", ascii: "[partial differential]", unicode: "∂" },
    "alefsym" => Entity { name: "alefsym", latex: "\\aleph", latex_mathp: true, html: "&alefsym;", ascii: "aleph", unicode: "ℵ" },
    "ETH" => Entity { name: "ETH", latex: "\\DH{}", latex_mathp: false, html: "&ETH;", ascii: "D", unicode: "Ð" },
    "eth" => Entity { name: "eth", latex: "\\dh{}", latex_mathp: false, html: "&eth;", ascii: "dh", unicode: "ð" },
    "THORN" => Entity { name: "THORN", latex: "\\TH{}", latex_mathp: false, html: "&THORN;", ascii: "TH", unicode: "Þ" },
    "thorn" => Entity { name: "thorn", latex: "\\th{}", latex_mathp: false, html: "&thorn;", ascii: "th", unicode: "þ" },
    "dots" => Entity { name: "dots", latex: "\\dots{}", latex_mathp: false, html: "&hellip;", ascii: "...", unicode: "…" },
    "hellip" => Entity { name: "hellip", latex: "\\dots{}", latex_mathp: false, html: "&hellip;", ascii: "...", unicode: "…" },
    "middot" => Entity { name: "middot", latex: "\\textperiodcentered{}", latex_mathp: false, html: "&middot;", ascii: ".", unicode: "·" },
    "iexcl" => Entity { name: "iexcl", latex: "!`", latex_mathp: false, html: "&iexcl;", ascii: "!", unicode: "¡" },
    "iquest" => Entity { name: "iquest", latex: "?`", latex_mathp: false, html: "&iquest;", ascii: "?", unicode: "¿" },
    "shy" => Entity { name: "shy", latex: "\\-", latex_mathp: false, html: "&shy;", ascii: "", unicode: "" },
    "ndash" => Entity { name: "ndash", latex: "--", latex_mathp: false, html: "&ndash;", ascii: "-", unicode: "–" },
    "mdash" => Entity { name: "mdash", latex: "---", latex_mathp: false, html: "&mdash;", ascii: "--", unicode: "—" },
    "quot" => Entity { name: "quot", latex: "\\textquotedbl{}", latex_mathp: false, html: "&quot;", ascii: "\"", unicode: "\"" },
    "acute" => Entity { name: "acute", latex: "\\textasciiacute{}", latex_mathp: false, html: "&acute;", ascii: "'", unicode: "´" },
    "ldquo" => Entity { name: "ldquo", latex: "\\textquotedblleft{}", latex_mathp: false, html: "&ldquo;", ascii: "\"", unicode: "“" },
    "rdquo" => Entity { name: "rdquo", latex: "\\textquotedblright{}", latex_mathp: false, html: "&rdquo;", ascii: "\"", unicode: "”" },
    "bdquo" => Entity { name: "bdquo", latex: "\\quotedblbase{}", latex_mathp: false, html: "&bdquo;", ascii: "\"", unicode: "„" },
    "lsquo" => Entity { name: "lsquo", latex: "\\textquoteleft{}", latex_mathp: false, html: "&lsquo;", ascii: "`", unicode: "‘" },
    "rsquo" => Entity { name: "rsquo", latex: "\\textquoteright{}", latex_mathp: false, html: "&rsquo;", ascii: "'", unicode: "’" },
    "sbquo" => Entity { name: "sbquo", latex: "\\quotesinglbase{}", latex_mathp: false, html: "&sbquo;", ascii: ",", unicode: "‚" },
    "laquo" => Entity { name: "laquo", latex: "\\guillemotleft{}", latex_mathp: false, html: "&laquo;", ascii: "<<", unicode: "«" },
    "raquo" => Entity { name: "raquo", latex: "\\guillemotright{}", latex_mathp: false, html: "&raquo;", ascii: ">>", unicode: "»" },
    "lsaquo" => Entity { name: "lsaquo", latex: "\\guilsinglleft{}", latex_mathp: false, html: "&lsaquo;", ascii: "<", unicode: "‹" },
    "rsaquo" => Entity { name: "rsaquo", latex: "\\guilsinglright{}", latex_mathp: false, html: "&rsaquo;", ascii: ">", unicode: "›" },
    "circ" => Entity { name: "circ", latex: "\\circ", latex_mathp: true, html: "&circ;", ascii: "^", unicode: "ˆ" },
    "vert" => Entity { name: "vert", latex: "\\vert{}", latex_mathp: true, html: "&#124;", ascii: "|", unicode: "|" },
    "brvbar" => Entity { name: "brvbar", latex: "\\textbrokenbar{}", latex_mathp: false, html: "&brvbar;", ascii: "|", unicode: "¦" },
    "sect" => Entity { name: "sect", latex: "\\S", latex_mathp: false, html: "&sect;", ascii: "paragraph", unicode: "§" },
    "amp" => Entity { name: "amp", latex: "\\&", latex_mathp: false, html: "&amp;", ascii: "&", unicode: "&" },
    "lt" => Entity { name: "lt", latex: "\\textless{}", latex_mathp: false, html: "&lt;", ascii: "<", unicode: "<" },
    "gt" => Entity { name: "gt", latex: "\\textgreater{}", latex_mathp: false, html: "&gt;", ascii: ">", unicode: ">" },
    "tilde" => Entity { name: "tilde", latex: "\\~{}", latex_mathp: false, html: "&tilde;", ascii: "~", unicode: "~" },
    "dagger" => Entity { name: "dagger", latex: "\\textdagger{}", latex_mathp: false, html: "&dagger;", ascii: "[dagger]", unicode: "†" },
    "Dagger" => Entity { name: "Dagger", latex: "\\textdaggerdbl{}", latex_mathp: false, html: "&Dagger;", ascii: "[doubledagger]", unicode: "‡" },
    "nbsp" => Entity { name: "nbsp", latex: "~", latex_mathp: false, html: "&nbsp;", ascii: " ", unicode: " " },
    "ensp" => Entity { name: "ensp", latex: "\\hspace*{.5em}", latex_mathp: false, html: "&ensp;", ascii: " ", unicode: " " },
    "emsp" => Entity { name: "emsp", latex: "\\hspace*{1em}", latex_mathp: false, html: "&emsp;", ascii: " ", unicode: " " },
    "thinsp" => Entity { name: "thinsp", latex: "\\hspace*{.2em}", latex_mathp: false, html: "&thinsp;", ascii: " ", unicode: " " },
    "curren" => Entity { name: "curren", latex: "\\textcurrency{}", latex_mathp: false, html: "&curren;", ascii: "curr.", unicode: "¤" },
    "cent" => Entity { name: "cent", latex: "\\textcent{}", latex_mathp: false, html: "&cent;", ascii: "cent", unicode: "¢" },
    "pound" => Entity { name: "pound", latex: "\\pounds{}", latex_mathp: false, html: "&pound;", ascii: "pound", unicode: "£" },
    "yen" => Entity { name: "yen", latex: "\\textyen{}", latex_mathp: false, html: "&yen;", ascii: "yen", unicode: "¥" },
    "euro" => Entity { name: "euro", latex: "\\texteuro{}", latex_mathp: false, html: "&euro;", ascii: "EUR", unicode: "€" },
    "EUR" => Entity { name: "EUR", latex: "\\EUR{}", latex_mathp: false, html: "&euro;", ascii: "EUR", unicode: "€" },
    "EURdig" => Entity { name: "EURdig", latex: "\\EURdig{}", latex_mathp: false, html: "&euro;", ascii: "EUR", unicode: "€" },
    "EURhv" => Entity { name: "EURhv", latex: "\\EURhv{}", latex_mathp: false, html: "&euro;", ascii: "EUR", unicode: "€" },
    "EURcr" => Entity { name: "EURcr", latex: "\\EURcr{}", latex_mathp: false, html: "&euro;", ascii: "EUR", unicode: "€" },
    "EURtm" => Entity { name: "EURtm", latex: "\\EURtm{}", latex_mathp: false, html: "&euro;", ascii: "EUR", unicode: "€" },
    "copy" => Entity { name: "copy", latex: "\\textcopyright{}", latex_mathp: false, html: "&copy;", ascii: "(c)", unicode: "©" },
    "reg" => Entity { name: "reg", latex: "\\textregistered{}", latex_mathp: false, html: "&reg;", ascii: "(r)", unicode: "®" },
    "trade" => Entity { name: "trade", latex: "\\texttrademark{}", latex_mathp: false, html: "&trade;", ascii: "TM", unicode: "™" },
    "minus" => Entity { name: "minus", latex: "\\minus", latex_mathp: true, html: "&minus;", ascii: "-", unicode: "−" },
    "pm" => Entity { name: "pm", latex: "\\textpm{}", latex_mathp: false, html: "&plusmn;", ascii: "+-", unicode: "±" },
    "plusmn" => Entity { name: "plusmn", latex: "\\textpm{}", latex_mathp: false, html: "&plusmn;", ascii: "+-", unicode: "±" },
    "times" => Entity { name: "times", latex: "\\texttimes{}", latex_mathp: false, html: "&times;", ascii: "*", unicode: "×" },
    "frasl" => Entity { name: "frasl", latex: "/", latex_mathp: false, html: "&frasl;", ascii: "/", unicode: "⁄" },
    "div" => Entity { name: "div", latex: "\\textdiv{}", latex_mathp: false, html: "&divide;", ascii: "/", unicode: "÷" },
    "frac12" => Entity { name: "frac12", latex: "\\textonehalf{}", latex_mathp: false, html: "&frac12;", ascii: "1/2", unicode: "½" },
    "frac14" => Entity { name: "frac14", latex: "\\textonequarter{}", latex_mathp: false, html: "&frac14;", ascii: "1/4", unicode: "¼" },
    "frac34" => Entity { name: "frac34", latex: "\\textthreequarters{}", latex_mathp: false, html: "&frac34;", ascii: "3/4", unicode: "¾" },
    "permil" => Entity { name: "permil", latex: "\\textperthousand{}", latex_mathp: false, html: "&permil;", ascii: "per thousand", unicode: "‰" },
    "sup1" => Entity { name: "sup1", latex: "\\textonesuperior{}", latex_mathp: false, html: "&sup1;", ascii: "^1", unicode: "¹" },
    "sup2" => Entity { name: "sup2", latex: "\\texttwosuperior{}", latex_mathp: false, html: "&sup2;", ascii: "^2", unicode: "²" },
    "sup3" => Entity { name: "sup3", latex: "\\textthreesuperior{}", latex_mathp: false, html: "&sup3;", ascii: "^3", unicode: "³" },
    "radic" => Entity { name: "radic", latex: "\\sqrt{\\,}", latex_mathp: true, html: "&radic;", ascii: "[square root]", unicode: "√" },
    "sum" => Entity { name: "sum", latex: "\\sum", latex_mathp: true, html: "&sum;", ascii: "[sum]", unicode: "∑" },
    "prod" => Entity { name: "prod", latex: "\\prod", latex_mathp: true, html: "&prod;", ascii: "[product]", unicode: "∏" },
    "micro" => Entity { name: "micro", latex: "\\textmu{}", latex_mathp: false, html: "&micro;", ascii: "micro", unicode: "µ" },
    "macr" => Entity { name: "macr", latex: "\\textasciimacron{}", latex_mathp: false, html: "&macr;", ascii: "[macron]", unicode: "¯" },
    "deg" => Entity { name: "deg", latex: "\\deg", latex_mathp: true, html: "&deg;", ascii: "deg", unicode: "deg" },
    "prime" => Entity { name: "prime", latex: "\\prime", latex_mathp: true, html: "&prime;", ascii: "'", unicode: "′" },
    "Prime" => Entity { name: "Prime", latex: "\\prime{}\\prime", latex_mathp: true, html: "&Prime;", ascii: "''", unicode: "″" },
    "infin" => Entity { name: "infin", latex: "\\propto", latex_mathp: true, html: "&infin;", ascii: "[infinity]", unicode: "∞" },
    "infty" => Entity { name: "infty", latex: "\\infty", latex_mathp: true, html: "&infin;", ascii: "[infinity]", unicode: "∞" },
    "prop" => Entity { name: "prop", latex: "\\propto", latex_mathp: true, html: "&prop;", ascii: "[proportional to]", unicode: "∝" },
    "proptp" => Entity { name: "proptp", latex: "\\propto", latex_mathp: true, html: "&prop;", ascii: "[proportional to]", unicode: "∝" },
    "not" => Entity { name: "not", latex: "\\textlnot{}", latex_mathp: false, html: "&not;", ascii: "[angled dash]", unicode: "¬" },
    "land" => Entity { name: "land", latex: "\\land", latex_mathp: true, html: "&and;", ascii: "[logical and]", unicode: "∧" },
    "wedge" => Entity { name: "wedge", latex: "\\wedge", latex_mathp: true, html: "&and;", ascii: "[logical and]", unicode: "∧" },
    "lor" => Entity { name: "lor", latex: "\\lor", latex_mathp: true, html: "&or;", ascii: "[logical or]", unicode: "∨" },
    "vee" => Entity { name: "vee", latex: "\\vee", latex_mathp: true, html: "&or;", ascii: "[logical or]", unicode: "∨" },
    "cap" => Entity { name: "cap", latex: "\\cap", latex_mathp: true, html: "&cap;", ascii: "[intersection]", unicode: "∩" },
    "cup" => Entity { name: "cup", latex: "\\cup", latex_mathp: true, html: "&cup;", ascii: "[union]", unicode: "∪" },
    "int" => Entity { name: "int", latex: "\\int", latex_mathp: true, html: "&int;", ascii: "[integral]", unicode: "∫" },
    "there4" => Entity { name: "there4", latex: "\\therefore", latex_mathp: true, html: "&there4;", ascii: "[therefore]", unicode: "∴" },
    "sim" => Entity { name: "sim", latex: "\\sim", latex_mathp: true, html: "&sim;", ascii: "~", unicode: "∼" },
    "cong" => Entity { name: "cong", latex: "\\cong", latex_mathp: true, html: "&cong;", ascii: "[approx. equal to]", unicode: "≅" },
    "simeq" => Entity { name: "simeq", latex: "\\simeq", latex_mathp: true, html: "&cong;", ascii: "[approx. equal to]", unicode: "≅" },
    "asymp" => Entity { name: "asymp", latex: "\\asymp", latex_mathp: true, html: "&asymp;", ascii: "[almost equal to]", unicode: "≈" },
    "approx" => Entity { name: "approx", latex: "\\approx", latex_mathp: true, html: "&asymp;", ascii: "[almost equal to]", unicode: "≈" },
    "ne" => Entity { name: "ne", latex: "\\ne", latex_mathp: true, html: "&ne;", ascii: "[not equal to]", unicode: "≠" },
    "neq" => Entity { name: "neq", latex: "\\neq", latex_mathp: true, html: "&ne;", ascii: "[not equal to]", unicode: "≠" },
    "equiv" => Entity { name: "equiv", latex: "\\equiv", latex_mathp: true, html: "&equiv;", ascii: "[identical to]", unicode: "≡" },
    "le" => Entity { name: "le", latex: "\\le", latex_mathp: true, html: "&le;", ascii: "<=", unicode: "≤" },
    "ge" => Entity { name: "ge", latex: "\\ge", latex_mathp: true, html: "&ge;", ascii: ">=", unicode: "≥" },
    "sub" => Entity { name: "sub", latex: "\\subset", latex_mathp: true, html: "&sub;", ascii: "[subset of]", unicode: "⊂" },
    "subset" => Entity { name: "subset", latex: "\\subset", latex_mathp: true, html: "&sub;", ascii: "[subset of]", unicode: "⊂" },
    "sup" => Entity { name: "sup", latex: "\\sup", latex_mathp: true, html: "&sup;", ascii: "sup", unicode: "sup" },
    "supset" => Entity { name: "supset", latex: "\\supset", latex_mathp: true, html: "&sup;", ascii: "[superset of]", unicode: "⊃" },
    "nsub" => Entity { name: "nsub", latex: "\\not\\subset", latex_mathp: true, html: "&nsub;", ascii: "[not a subset of]", unicode: "⊄" },
    "sube" => Entity { name: "sube", latex: "\\subseteq", latex_mathp: true, html: "&sube;", ascii: "[subset of or equal to]", unicode: "⊆" },
    "nsup" => Entity { name: "nsup", latex: "\\not\\supset", latex_mathp: true, html: "&nsup;", ascii: "[not a superset of]", unicode: "⊅" },
    "supe" => Entity { name: "supe", latex: "\\supseteq", latex_mathp: true, html: "&supe;", ascii: "[superset of or equal to]", unicode: "⊇" },
    "forall" => Entity { name: "forall", latex: "\\forall", latex_mathp: true, html: "&forall;", ascii: "[for all]", unicode: "∀" },
    "exist" => Entity { name: "exist", latex: "\\exists", latex_mathp: true, html: "&exist;", ascii: "[there exists]", unicode: "∃" },
    "exists" => Entity { name: "exists", latex: "\\exists", latex_mathp: true, html: "&exist;", ascii: "[there exists]", unicode: "∃" },
    "empty" => Entity { name: "empty", latex: "\\empty", latex_mathp: true, html: "&empty;", ascii: "[empty set]", unicode: "∅" },
    "emptyset" => Entity { name: "emptyset", latex: "\\emptyset", latex_mathp: true, html: "&empty;", ascii: "[empty set]", unicode: "∅" },
    "isin" => Entity { name: "isin", latex: "\\in", latex_mathp: true, html: "&isin;", ascii: "[element of]", unicode: "∈" },
    "in" => Entity { name: "in", latex: "\\in", latex_mathp: true, html: "&isin;", ascii: "[element of]", unicode: "∈" },
    "notin" => Entity { name: "notin", latex: "\\notin", latex_mathp: true, html: "&notin;", ascii: "[not an element of]", unicode: "∉" },
    "ni" => Entity { name: "ni", latex: "\\ni", latex_mathp: true, html: "&ni;", ascii: "[contains as member]", unicode: "∋" },
    "nabla" => Entity { name: "nabla", latex: "\\nabla", latex_mathp: true, html: "&nabla;", ascii: "[nabla]", unicode: "∇" },
    "ang" => Entity { name: "ang", latex: "\\angle", latex_mathp: true, html: "&ang;", ascii: "[angle]", unicode: "∠" },
    "angle" => Entity { name: "angle", latex: "\\angle", latex_mathp: true, html: "&ang;", ascii: "[angle]", unicode: "∠" },
    "perp" => Entity { name: "perp", latex: "\\perp", latex_mathp: true, html: "&perp;", ascii: "[up tack]", unicode: "⊥" },
    "sdot" => Entity { name: "sdot", latex: "\\cdot", latex_mathp: true, html: "&sdot;", ascii: "[dot]", unicode: "⋅" },
    "cdot" => Entity { name: "cdot", latex: "\\cdot", latex_mathp: true, html: "&sdot;", ascii: "[dot]", unicode: "⋅" },
    "lceil" => Entity { name: "lceil", latex: "\\lceil", latex_mathp: true, html: "&lceil;", ascii: "[left ceiling]", unicode: "⌈" },
    "rceil" => Entity { name: "rceil", latex: "\\rceil", latex_mathp: true, html: "&rceil;", ascii: "[right ceiling]", unicode: "⌉" },
    "lfloor" => Entity { name: "lfloor", latex: "\\lfloor", latex_mathp: true, html: "&lfloor;", ascii: "[left floor]", unicode: "⌊" },
    "rfloor" => Entity { name: "rfloor", latex: "\\rfloor", latex_mathp: true, html: "&rfloor;", ascii: "[right floor]", unicode: "⌋" },
    "lang" => Entity { name: "lang", latex: "\\langle", latex_mathp: true, html: "&lang;", ascii: "<", unicode: "⟨" },
    "rang" => Entity { name: "rang", latex: "\\rangle", latex_mathp: true, html: "&rang;", ascii: ">", unicode: "⟩" },
    "larr" => Entity { name: "larr", latex: "\\leftarrow", latex_mathp: true, html: "&larr;", ascii: "<-", unicode: "←" },
    "leftarrow" => Entity { name: "leftarrow", latex: "\\leftarrow", latex_mathp: true, html: "&larr;", ascii: "<-", unicode: "←" },
    "gets" => Entity { name: "gets", latex: "\\gets", latex_mathp: true, html: "&larr;", ascii: "<-", unicode: "←" },
    "lArr" => Entity { name: "lArr", latex: "\\Leftarrow", latex_mathp: true, html: "&lArr;", ascii: "<=", unicode: "⇐" },
    "Leftarrow" => Entity { name: "Leftarrow", latex: "\\Leftarrow", latex_mathp: true, html: "&lArr;", ascii: "<=", unicode: "⇐" },
    "uarr" => Entity { name: "uarr", latex: "\\uparrow", latex_mathp: true, html: "&uarr;", ascii: "[uparrow]", unicode: "↑" },
    "uparrow" => Entity { name: "uparrow", latex: "\\uparrow", latex_mathp: true, html: "&uarr;", ascii: "[uparrow]", unicode: "↑" },
    "uArr" => Entity { name: "uArr", latex: "\\Uparrow", latex_mathp: true, html: "&uArr;", ascii: "[dbluparrow]", unicode: "⇑" },
    "Uparrow" => Entity { name: "Uparrow", latex: "\\Uparrow", latex_mathp: true, html: "&uArr;", ascii: "[dbluparrow]", unicode: "⇑" },
    "rarr" => Entity { name: "rarr", latex: "\\rightarrow", latex_mathp: true, html: "&rarr;", ascii: "->", unicode: "→" },
    "to" => Entity { name: "to", latex: "\\to", latex_mathp: true, html: "&rarr;", ascii: "->", unicode: "→" },
    "rightarrow" => Entity { name: "rightarrow", latex: "\\rightarrow", latex_mathp: true, html: "&rarr;", ascii: "->", unicode: "→" },
    "rArr" => Entity { name: "rArr", latex: "\\Rightarrow", latex_mathp: true, html: "&rArr;", ascii: "=>", unicode: "⇒" },
    "Rightarrow" => Entity { name: "Rightarrow", latex: "\\Rightarrow", latex_mathp: true, html: "&rArr;", ascii: "=>", unicode: "⇒" },
    "darr" => Entity { name: "darr", latex: "\\downarrow", latex_mathp: true, html: "&darr;", ascii: "[downarrow]", unicode: "↓" },
    "downarrow" => Entity { name: "downarrow", latex: "\\downarrow", latex_mathp: true, html: "&darr;", ascii: "[downarrow]", unicode: "↓" },
    "dArr" => Entity { name: "dArr", latex: "\\Downarrow", latex_mathp: true, html: "&dArr;", ascii: "[dbldownarrow]", unicode: "⇓" },
    "Downarrow" => Entity { name: "Downarrow", latex: "\\Downarrow", latex_mathp: true, html: "&dArr;", ascii: "[dbldownarrow]", unicode: "⇓" },
    "harr" => Entity { name: "harr", latex: "\\leftrightarrow", latex_mathp: true, html: "&harr;", ascii: "<->", unicode: "↔" },
    "leftrightarrow" => Entity { name: "leftrightarrow", latex: "\\leftrightarrow", latex_mathp: true, html: "&harr;", ascii: "<->", unicode: "↔" },
    "hArr" => Entity { name: "hArr", latex: "\\Leftrightarrow", latex_mathp: true, html: "&hArr;", ascii: "<=>", unicode: "⇔" },
    "Leftrightarrow" => Entity { name: "Leftrightarrow", latex: "\\Leftrightarrow", latex_mathp: true, html: "&hArr;", ascii: "<=>", unicode: "⇔" },
    "crarr" => Entity { name: "crarr", latex: "\\hookleftarrow", latex_mathp: true, html: "&crarr;", ascii: "<-'", unicode: "↵" },
    "hookleftarrow" => Entity { name: "hookleftarrow", latex: "\\hookleftarrow", latex_mathp: true, html: "&crarr;", ascii: "<-'", unicode: "↵" },
    "arccos" => Entity { name: "arccos", latex: "\\arccos", latex_mathp: true, html: "arccos", ascii: "arccos", unicode: "arccos" },
    "arcsin" => Entity { name: "arcsin", latex: "\\arcsin", latex_mathp: true, html: "arcsin", ascii: "arcsin", unicode: "arcsin" },
    "arctan" => Entity { name: "arctan", latex: "\\arctan", latex_mathp: true, html: "arctan", ascii: "arctan", unicode: "arctan" },
    "arg" => Entity { name: "arg", latex: "\\arg", latex_mathp: true, html: "arg", ascii: "arg", unicode: "arg" },
    "cos" => Entity { name: "cos", latex: "\\cos", latex_mathp: true, html: "cos", ascii: "cos", unicode: "cos" },
    "cosh" => Entity { name: "cosh", latex: "\\cosh", latex_mathp: true, html: "cosh", ascii: "cosh", unicode: "cosh" },
    "cot" => Entity { name: "cot", latex: "\\cot", latex_mathp: true, html: "cot", ascii: "cot", unicode: "cot" },
    "coth" => Entity { name: "coth", latex: "\\coth", latex_mathp: true, html: "coth", ascii: "coth", unicode: "coth" },
    "csc" => Entity { name: "csc", latex: "\\csc", latex_mathp: true, html: "csc", ascii: "csc", unicode: "csc" },
    "det" => Entity { name: "det", latex: "\\det", latex_mathp: true, html: "det", ascii: "det", unicode: "det" },
    "dim" => Entity { name: "dim", latex: "\\dim", latex_mathp: true, html: "dim", ascii: "dim", unicode: "dim" },
    "exp" => Entity { name: "exp", latex: "\\exp", latex_mathp: true, html: "exp", ascii: "exp", unicode: "exp" },
    "gcd" => Entity { name: "gcd", latex: "\\gcd", latex_mathp: true, html: "gcd", ascii: "gcd", unicode: "gcd" },
    "hom" => Entity { name: "hom", latex: "\\hom", latex_mathp: true, html: "hom", ascii: "hom", unicode: "hom" },
    "inf" => Entity { name: "inf", latex: "\\inf", latex_mathp: true, html: "inf", ascii: "inf", unicode: "inf" },
    "ker" => Entity { name: "ker", latex: "\\ker", latex_mathp: true, html: "ker", ascii: "ker", unicode: "ker" },
    "lg" => Entity { name: "lg", latex: "\\lg", latex_mathp: true, html: "lg", ascii: "lg", unicode: "lg" },
    "lim" => Entity { name: "lim", latex: "\\lim", latex_mathp: true, html: "lim", ascii: "lim", unicode: "lim" },
    "liminf" => Entity { name: "liminf", latex: "\\liminf", latex_mathp: true, html: "liminf", ascii: "liminf", unicode: "liminf" },
    "limsup" => Entity { name: "limsup", latex: "\\limsup", latex_mathp: true, html: "limsup", ascii: "limsup", unicode: "limsup" },
    "ln" => Entity { name: "ln", latex: "\\ln", latex_mathp: true, html: "ln", ascii: "ln", unicode: "ln" },
    "log" => Entity { name: "log", latex: "\\log", latex_mathp: true, html: "log", ascii: "log", unicode: "log" },
    "max" => Entity { name: "max", latex: "\\max", latex_mathp: true, html: "max", ascii: "max", unicode: "max" },
    "min" => Entity { name: "min", latex: "\\min", latex_mathp: true, html: "min", ascii: "min", unicode: "min" },
    "Pr" => Entity { name: "Pr", latex: "\\Pr", latex_mathp: true, html: "Pr", ascii: "Pr", unicode: "Pr" },
    "sec" => Entity { name: "sec", latex: "\\sec", latex_mathp: true, html: "sec", ascii: "sec", unicode: "sec" },
    "sin" => Entity { name: "sin", latex: "\\sin", latex_mathp: true, html: "sin", ascii: "sin", unicode: "sin" },
    "sinh" => Entity { name: "sinh", latex: "\\sinh", latex_mathp: true, html: "sinh", ascii: "sinh", unicode: "sinh" },
    "tan" => Entity { name: "tan", latex: "\\tan", latex_mathp: true, html: "tan", ascii: "tan", unicode: "tan" },
    "tanh" => Entity { name: "tanh", latex: "\\tanh", latex_mathp: true, html: "tanh", ascii: "tanh", unicode: "tanh" },
    "bull" => Entity { name: "bull", latex: "\\textbullet{}", latex_mathp: false, html: "&bull;", ascii: "*", unicode: "•" },
    "bullet" => Entity { name: "bullet", latex: "\\textbullet{}", latex_mathp: false, html: "&bull;", ascii: "*", unicode: "•" },
    "star" => Entity { name: "star", latex: "\\star", latex_mathp: true, html: "*", ascii: "*", unicode: "⋆" },
    "lowast" => Entity { name: "lowast", latex: "\\ast", latex_mathp: true, html: "&lowast;", ascii: "*", unicode: "∗" },
    "ast" => Entity { name: "ast", latex: "\\ast", latex_mathp: true, html: "&lowast;", ascii: "*", unicode: "*" },
    "odot" => Entity { name: "odot", latex: "\\odot", latex_mathp: true, html: "o", ascii: "[circled dot]", unicode: "ʘ" },
    "oplus" => Entity { name: "oplus", latex: "\\oplus", latex_mathp: true, html: "&oplus;", ascii: "[circled plus]", unicode: "⊕" },
    "otimes" => Entity { name: "otimes", latex: "\\otimes", latex_mathp: true, html: "&otimes;", ascii: "[circled times]", unicode: "⊗" },
    "checkmark" => Entity { name: "checkmark", latex: "\\checkmark", latex_mathp: true, html: "&#10003;", ascii: "[checkmark]", unicode: "✓" },
    "para" => Entity { name: "para", latex: "\\P{}", latex_mathp: false, html: "&para;", ascii: "[pilcrow]", unicode: "¶" },
    "ordf" => Entity { name: "ordf", latex: "\\textordfeminine{}", latex_mathp: false, html: "&ordf;", ascii: "_a_", unicode: "ª" },
    "ordm" => Entity { name: "ordm", latex: "\\textordmasculine{}", latex_mathp: false, html: "&ordm;", ascii: "_o_", unicode: "º" },
    "cedil" => Entity { name: "cedil", latex: "\\c{}", latex_mathp: false, html: "&cedil;", ascii: "[cedilla]", unicode: "¸" },
    "oline" => Entity { name: "oline", latex: "\\overline{~}", latex_mathp: true, html: "&oline;", ascii: "[overline]", unicode: "‾" },
    "uml" => Entity { name: "uml", latex: "\\textasciidieresis{}", latex_mathp: false, html: "&uml;", ascii: "[diaeresis]", unicode: "¨" },
    "zwnj" => Entity { name: "zwnj", latex: "\\/{}", latex_mathp: false, html: "&zwnj;", ascii: "", unicode: "‌" },
    "zwj" => Entity { name: "zwj", latex: "", latex_mathp: false, html: "&zwj;", ascii: "", unicode: "‍" },
    "lrm" => Entity { name: "lrm", latex: "", latex_mathp: false, html: "&lrm;", ascii: "", unicode: "‎" },
    "rlm" => Entity { name: "rlm", latex: "", latex_mathp: false, html: "&rlm;", ascii: "", unicode: "‏" },
    "smile" => Entity { name: "smile", latex: "\\smile", latex_mathp: true, html: "&#9786;", ascii: ":-)", unicode: "⌣" },
    "smiley" => Entity { name: "smiley", latex: "\\smiley{}", latex_mathp: false, html: "&#9786;", ascii: ":-)", unicode: "☺" },
    "blacksmile" => Entity { name: "blacksmile", latex: "\\blacksmiley{}", latex_mathp: false, html: "&#9787;", ascii: ":-)", unicode: "☻" },
    "sad" => Entity { name: "sad", latex: "\\frownie{}", latex_mathp: false, html: "&#9785;", ascii: ":-(", unicode: "☹" },
    "clubs" => Entity { name: "clubs", latex: "\\clubsuit", latex_mathp: true, html: "&clubs;", ascii: "[clubs]", unicode: "♣" },
    "clubsuit" => Entity { name: "clubsuit", latex: "\\clubsuit", latex_mathp: true, html: "&clubs;", ascii: "[clubs]", unicode: "♣" },
    "spades" => Entity { name: "spades", latex: "\\spadesuit", latex_mathp: true, html: "&spades;", ascii: "[spades]", unicode: "♠" },
    "spadesuit" => Entity { name: "spadesuit", latex: "\\spadesuit", latex_mathp: true, html: "&spades;", ascii: "[spades]", unicode: "♠" },
    "hearts" => Entity { name: "hearts", latex: "\\heartsuit", latex_mathp: true, html: "&hearts;", ascii: "[hearts]", unicode: "♥" },
    "heartsuit" => Entity { name: "heartsuit", latex: "\\heartsuit", latex_mathp: true, html: "&heartsuit;", ascii: "[hearts]", unicode: "♥" },
    "diams" => Entity { name: "diams", latex: "\\diamondsuit", latex_mathp: true, html: "&diams;", ascii: "[diamonds]", unicode: "♦" },
    "diamondsuit" => Entity { name: "diamondsuit", latex: "\\diamondsuit", latex_mathp: true, html: "&diams;", ascii: "[diamonds]", unicode: "♦" },
    "Diamond" => Entity { name: "Diamond", latex: "\\diamond", latex_mathp: true, html: "&diamond;", ascii: "[diamond]", unicode: "⋄" },
    "loz" => Entity { name: "loz", latex: "\\diamond", latex_mathp: true, html: "&loz;", ascii: "[lozenge]", unicode: "◊" }
};
